spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecsite
    username: postgres
    password: postgres
  jmx:
    default-domain: ecsite-api
server:
  servlet:
    context-path: /ecsite-api